"""Context window manager with sliding window and LLM-based summarization.

Sits between the agent loop and the LLM call, trimming ``messages`` to
fit within the configured token budget.  When the conversation exceeds
the summarization threshold, older messages are compressed into a short
summary generated by a cheap LLM call.
"""

from __future__ import annotations

from typing import Any

from rich.console import Console

from agent.tokens import count_messages, count_tokens
from config.settings import ContextSettings


class ContextManager:
    """Manage the conversation context to stay within token limits.

    Strategy:
    1. System prompt always stays (index 0).
    2. Keep the last ``keep_recent`` user+assistant+tool exchange groups.
    3. If total tokens > ``effective_target * summarize_threshold``:
       - Ask the LLM to summarize older messages.
       - Replace them with a single system-level summary message.
    4. If still over budget after summarization, aggressively truncate
       tool results (keep first + last lines).
    """

    # Prompt used to ask the LLM to summarize conversation history
    _SUMMARIZE_PROMPT = (
        "Summarize the following conversation between a user and an AI coding agent. "
        "Focus on: what the user asked, what files were read/edited, what commands ran, "
        "and the final outcome. Be concise — under 300 words.\n\n"
    )

    def __init__(
        self,
        settings: ContextSettings,
        console: Console | None = None,
    ) -> None:
        self.effective_target = settings.effective_context_target
        self.keep_recent = settings.keep_recent_messages
        self.summarize_threshold = settings.summarize_threshold
        self._console = console or Console()
        self._current_summary: str | None = None
        # Will be set externally by the agent so we can make summarization calls
        self._provider: Any = None

    def set_provider(self, provider: Any) -> None:
        """Inject the LLM provider for summarization calls."""
        self._provider = provider

    def prepare(self, messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Return a trimmed copy of messages that fits the token budget.

        Does NOT mutate the original list — the agent keeps the full
        history for its own bookkeeping.
        """
        token_count = count_messages(messages)
        threshold = int(self.effective_target * self.summarize_threshold)

        # Under threshold — pass through
        if token_count <= threshold:
            return list(messages)

        self._console.print(
            f"[dim]📦 Context at {token_count:,} tokens "
            f"(threshold {threshold:,}) — compressing...[/dim]"
        )

        # Split: system prompt | old history | recent messages
        system_msg = messages[0]  # always the system prompt
        recent_start = self._find_recent_start(messages)
        old_messages = messages[1:recent_start]
        recent_messages = messages[recent_start:]

        # Summarize old messages
        summary = self._summarize(old_messages)

        # Build the compressed message list
        compressed: list[dict[str, Any]] = [system_msg]

        if summary:
            compressed.append({
                "role": "system",
                "content": f"[Conversation summary so far]: {summary}",
            })

        compressed.extend(recent_messages)

        # If still over budget, truncate large tool results
        compressed = self._truncate_tool_results(compressed)

        new_count = count_messages(compressed)
        self._console.print(
            f"[dim]📦 Compressed to {new_count:,} tokens "
            f"({token_count - new_count:,} saved)[/dim]"
        )

        return compressed

    def _find_recent_start(self, messages: list[dict[str, Any]]) -> int:
        """Find the index where 'recent' messages begin.

        Walks backwards from the end, counting user messages (each user
        message + its subsequent assistant/tool messages = one exchange).
        Keeps ``keep_recent`` exchanges intact.
        """
        user_count = 0
        idx = len(messages)

        for i in range(len(messages) - 1, 0, -1):
            if messages[i].get("role") == "user":
                user_count += 1
                if user_count >= self.keep_recent:
                    idx = i
                    break

        return max(idx, 1)  # Never drop the system prompt

    def _summarize(self, old_messages: list[dict[str, Any]]) -> str:
        """Use the LLM to summarize old conversation messages."""
        if not old_messages:
            return self._current_summary or ""

        # Build a text representation of old messages
        parts: list[str] = []
        for msg in old_messages:
            role = msg.get("role", "?")
            content = msg.get("content", "")
            if isinstance(content, str) and content.strip():
                # Truncate very long tool results for the summary input
                if len(content) > 2000:
                    content = content[:1000] + "\n...[truncated]...\n" + content[-500:]
                parts.append(f"[{role}]: {content}")

        conversation_text = "\n".join(parts)

        # If we have a provider, use LLM summarization
        if self._provider is not None:
            try:
                response = self._provider.complete(
                    prompt=self._SUMMARIZE_PROMPT + conversation_text,
                    system_prompt="You are a conversation summarizer. Be concise and factual.",
                )
                summary = response.text.strip()
                if summary:
                    # Merge with previous summary if exists
                    if self._current_summary:
                        summary = f"{self._current_summary}\n\nMore recently: {summary}"
                    self._current_summary = summary
                    return summary
            except Exception:
                pass  # Fall through to text-based fallback

        # Fallback: just keep a truncated version
        fallback = conversation_text[:3000]
        self._current_summary = fallback
        return fallback

    def _truncate_tool_results(
        self, messages: list[dict[str, Any]]
    ) -> list[dict[str, Any]]:
        """Aggressively truncate long tool results if still over budget."""
        result: list[dict[str, Any]] = []
        for msg in messages:
            if msg.get("role") == "tool":
                content = msg.get("content", "")
                if isinstance(content, str) and count_tokens(content) > 1000:
                    lines = content.splitlines()
                    if len(lines) > 30:
                        truncated = (
                            "\n".join(lines[:10])
                            + f"\n\n...[{len(lines) - 20} lines truncated]...\n\n"
                            + "\n".join(lines[-10:])
                        )
                        msg = {**msg, "content": truncated}
            result.append(msg)
        return result
